version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - webnet

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/task_db
    restart: always
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
    restart: always
    networks:
      - webnet

volumes:
  mongo_data:

networks:
  webnet:
    driver: bridge